---
named-filters:
  normal:
    - !markdown
    - !cues
  code:
    - !code
    - !markdown
    - !cues

template-cache: .template-cache

default-content-filters:
  normal

default-note-filters:
  normal

arrangement: horizontal
impress-config:
  transition-duration: 200
